/* ========== Reveal init ========== */
document.documentElement.classList.add('js-reveal');

/* Sticky nav */
const nav = document.getElementById('nav');
const onScroll = () => {
  if (window.scrollY > 24) nav.classList.add('scrolled');
  else nav.classList.remove('scrolled');
};
window.addEventListener('scroll', onScroll, {passive:true});
onScroll();

/* Reveal observer */
const io = new IntersectionObserver((entries) => {
  entries.forEach(e => {
    if (e.isIntersecting) {
      e.target.classList.add('in');
      io.unobserve(e.target);
    }
  });
}, {threshold:.05, rootMargin:'0px 0px 200px 0px'});
document.querySelectorAll('.reveal').forEach(el => io.observe(el));
window.addEventListener('load', () => {
  setTimeout(() => {
    document.querySelectorAll('.reveal:not(.in)').forEach(el => el.classList.add('in'));
  }, 1500);
});

/* Mobile menu */
const navToggle = document.querySelector('.nav-toggle');
const mobileMenu = document.querySelector('.mobile-menu');
if (navToggle && mobileMenu) {
  navToggle.addEventListener('click', () => mobileMenu.classList.add('open'));
  mobileMenu.querySelectorAll('a, .close-x').forEach(el => {
    el.addEventListener('click', () => mobileMenu.classList.remove('open'));
  });
}

/* Active nav-link tracking */
const sections = ['hero','promise','how-it-works','joey','pillars','pyramid','impact','contact'];
const links = document.querySelectorAll('.nav-links a, .mobile-menu a');
const sectionIo = new IntersectionObserver((entries) => {
  entries.forEach(e => {
    if (e.isIntersecting && e.intersectionRatio > .35) {
      const id = e.target.id;
      links.forEach(l => {
        const href = l.getAttribute('href');
        if (href === '#' + id) l.classList.add('active');
        else l.classList.remove('active');
      });
    }
  });
}, {threshold:[.35, .6]});
sections.forEach(id => {
  const el = document.getElementById(id);
  if (el) sectionIo.observe(el);
});

/* ================================================================
   PYRAMID — 10 tiers
================================================================ */
const tierData = {
  1: {
    role:'Student',
    tagline:'Goals, learning plan, reflection, and a daily guide.',
    workspace:{
      title:'Workspace Dashboard',
      bullets:[
        'System generated daily individual learning plans and seatwork generated by system',
        'Daily learning map checklist so students always know what to work on next',
        'Portfolio for learning artifacts, system-analyzed, daily interventions and seat work assigned by system',
        'Goal planning and progress check-ins with badges and tokens that recognize effort and persistence',
        'Digital reader\'s, writer\'s, math, and science notebooks',
        'Multi-level e-book library for every unit, daily reading assigned and analyzed by system'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      subtitle:'Learning that fits each child.',
      bullets:[
        'Personalized reading and writing practice',
        'Science-of-reading systematic sequential word-study system (phonics, grammar, vocabulary) matched to needs',
        'App to record daily reading for system analysis, comprehending conversation with Joey (running record and analysis sent to teacher)',
        'Targeted support during workshop time',
        'Skills applied across subjects'
      ]
    },
    coach:{
      title:'Virtual Coach',
      subtitle:'Joey — a friendly guide who supports focus and confidence.',
      bullets:[
        'Daily greeting and learning focus',
        'Step-by-step guidance through tasks',
        'Helps students understand what to focus on next',
        'Encourages goal setting and reflection',
        'Prompts productive learning habits',
        'Supports independence and responsibility',
        'Builds confidence over time',
        'Joey-guided learning games',
        'Celebration of progress'
      ]
    }
  },
  2: {
    role:'Family',
    tagline:'Visibility, shared goals, and actionable ways to support learning.',
    workspace:{
      title:'Workspace Dashboard',
      intro:'Dashboard provides a simple, organized view of a child\'s learning and support. Examples include:',
      bullets:[
        '<strong>Learning Overview</strong> — what students are learning and why it matters. Learning that builds, not resets',
        '<strong>Standards-Based Progress Views</strong> — growth over time, not just grades',
        '<strong>Student Portfolio Access</strong> — artifacts that show learning across years',
        '<strong>School Communications</strong> — messages and updates from the school',
        '<strong>Teacher &amp; Student Messaging</strong> — easy, appropriate communication'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      intro:'NorthStar includes a family learning system that offers short, practical learning experiences such as:',
      bullets:[
        '<strong>Understanding developmental milestones (PreK–6)</strong>',
        '<strong>Getting ready for middle school</strong>',
        '<strong>Setting your child up for homework success</strong>'
      ],
      outro:'These learning pathways help families understand how children learn and how to provide meaningful support at home — without pressure or blame.'
    },
    coach:{
      title:'Virtual Coach',
      subtitle:'Guidance at home — without guesswork.',
      intro:'NorthStar provides a <strong>virtual homework coach</strong> to support families during homework and independent learning time. The coach:',
      bullets:[
        'offers prompts and guidance',
        'helps families know how to help without reteaching',
        'supports routines, focus, and self-regulation'
      ],
      outro:'Families can support learning confidently — without needing to be content experts.'
    }
  },
  3: {
    role:'Teacher',
    tagline:'Classroom workflows + personalized growth + embedded tools.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>Tool groupings include:</strong>',
      bullets:[
        '<strong>Instructional Planning:</strong> lesson planning, differentiation supports, goal alignment, report cards',
        '<strong>Instructional Tools:</strong> full curriculum, learning tools & e-book library, conferring app',
        '<strong>Student Learning &amp; Progress:</strong> learning targets, progress monitoring, evidence collection',
        '<strong>Classroom Routine Tools:</strong> daily workflows, check-ins, reflection prompts',
        '<strong>Intervention &amp; Support Tools:</strong> documentation, collaboration with interventionists and coaches',
        '<strong>Communication &amp; Collaboration Tools:</strong> shared goals, notes, and aligned expectations'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      subtitle:'<strong>Micro-credentialing system</strong> Professional learning connected to student need.',
      bullets:[
        'PLC planning and goal-setting aligned to classroom practice and school priorities',
        'Begins with a <strong>self-assessment or needs assessment</strong>',
        'Asynchronous learning modules; generates certificates of learning used for license renewal',
        'Allows teachers to <strong>demonstrate learning through real classroom evidence</strong> reflection and growth',
        'Badges and certifications stored in a professional portfolio',
        'Supports <strong>continuous improvement</strong>, not one-and-done training'
      ]
    },
    coach:{
      title:'Virtual Coach',
      subtitle:'<strong>Virtual Systems Coach — Guide the Work</strong>',
      intro:'Every teacher has access to a <strong>virtual coach</strong> that helps navigate the day.<br/><br/>The coach:',
      bullets:[
        'Guides you through tools and routines at the right moment',
        'Surfaces next-step instructional guidance',
        'Helps translate professional learning into classroom action',
        'Supports consistency without micromanagement',
        'Reduces guesswork by clarifying "what matters most right now"',
        'Organizes daily learning artifacts',
        'Analyzes strengths and needs'
      ]
    }
  },
  4: {
    role:'Interventionist',
    tagline:'Progress monitoring, targeted supports, efficiency tools.',
    workspace:{
      title:'Workspace Dashboard',
      bullets:[
        'Intervention dashboard with student focus areas',
        'Team-meeting system app that guides intervention planning and automatically generates intervention schedules',
        'Targeted skill-based interventions',
        'NorthStar analyzes daily learning artifacts and generates interventions aligned to student needs and classroom instruction',
        'System generated student intervention profiles shared with classroom teacher and interventionist to align instruction movement between tiers as needs change'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      bullets:[
        'Micro-credentialing system',
        'PLC planning and goal-setting that guides teachers through',
        'Asynchronous learning modules generates certificates of learning used for license renewal',
        'Evidence-based intervention learning',
        'Real intervention artifacts',
        'Reflection and growth portfolios'
      ]
    },
    coach:{
      title:'Virtual Coach',
      intro:'Every teacher has access to a <strong>virtual systems coach</strong> that helps navigate the day.<br/><br/>The coach:',
      bullets:[
        'Guides you through tools and routines at the right moment',
        'Prompts reflection and next steps aligned to your goals',
        'Helps translate professional learning into classroom action',
        'Supports consistency without micromanagement',
        'Reduces guesswork by clarifying &ldquo;what matters most right now&rdquo;'
      ],
      outro:'Think of it as a steady, supportive presence — not another evaluator.'
    }
  },
  5: {
    role:'Coach',
    tagline:'Coaching tools, micro-credentials, and day-to-day guidance.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>Coach Dashboard &amp; Instructional Insight Tools</strong>',
      bullets:[
        'Instructional pattern views',
        'Coaching cycle tools',
        'Classroom video library',
        'Teacher learning and application views',
        'Paperless coaching logs',
        'classroom-level and grade-level learning trends',
        'visibility into instructional patterns',
        'coaching cycle documentation',
        'alignment to instructional priorities and standards',
        'progress tracking over time'
      ],
      outro:'Everything is connected — reducing fragmentation and guesswork.'
    },
    pathways:{
      title:'Learning Pathways',
      bullets:[
        'Micro-Credentialling system',
        'Coaching-focused learning',
        'Real coaching artifacts',
        'Reflection and professional portfolios',
        'Coaching videos'
      ]
    },
    coach:{
      title:'Virtual Coach',
      subtitle:'<strong>JOEY&rsquo;S ROLE FOR COACHES</strong><br/><em><strong>From Data to Direction</strong></em>',
      intro:'For coaches, Joey is the engine that turns daily learning into <strong>actionable coaching insight</strong>.<br/><br/>Joey:',
      bullets:[
        'analyzes student learning evidence across classrooms',
        'identifies patterns of strength and need over time',
        'connects student outcomes to instructional practices',
        'organizes insights by teacher, grade level, and standard',
        'highlights where coaching support will have the greatest impact'
      ],
      outro:'Joey does the heavy analytical work — <strong>coaches use their expertise to respond</strong>.'
    }
  },
  6: {
    role:'School Leadership Team',
    tagline:'Improvement planning, shared goals, and progress visibility.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>School Leadership Dashboard &amp; Team Tools</strong>',
      bullets:[
        'School-wide learning views',
        'Grade-level and PLC reports',
        'Leadership meeting tools',
        'Implementation growth indicators',
        'Barrier and enabler analysis'
      ],
      subtitle2:'<strong>2. Aligned Improvement Pathways</strong>',
      bullets2:[
        'Building continuous improvement plans',
        'Needs assessments',
        'Focused goals and action plans',
        'Guided meeting routines'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      subtitle:'<strong>Micro-Credentialing System</strong>',
      intro:'School leadership teams are supported through:',
      bullets:[
        'role-specific onboarding',
        'Collective leadership learning',
        'Shared artifacts and reflection',
        'Team leadership portfolios'
      ]
    },
    coach:{
      title:'Virtual Coach',
      intro:'For school leadership teams, Joey is the system intelligence that turns day-to-day learning into <strong>school-level clarity</strong>.<br/><br/>Joey:',
      bullets:[
        'aggregates student learning evidence across classrooms',
        'analyzes patterns of instructional practice and outcomes',
        'connects classroom learning to school goals and priorities',
        'organizes evidence by grade level, team, and standard',
        'highlights where support, coaching, or adjustment is needed'
      ],
      outro:'Joey surfaces insight — <strong>leadership teams decide how to respond</strong>.'
    }
  },
  7: {
    role:'School Admin',
    tagline:'Implementation, usage, and outcomes visibility.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>Principal Dashboard &amp; System Insight Tools</strong>',
      bullets:[
        'School-wide learning views',
        'Implementation growth indicators',
        'PLC and team reports',
        'Intervention and support views',
        'Leadership reflection tools'
      ],
      subtitle2:'<strong>Aligned Instructional &amp; Improvement Pathways</strong>',
      bullets2:[
        'Interactive building continuous improvement plans',
        'Meeting agendas and action plans',
        'PLC and coaching alignment'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      subtitle:'<strong>Micro-Credentialing System</strong>',
      bullets:[
        'Needs Assessment and goal setting',
        'Leadership learning aligned to school goals',
        'Real leadership artifacts',
        'Reflection and leadership portfolios'
      ]
    },
    coach:{
      title:'Virtual Coach',
      subtitle:'<strong>Virtual Systems Coach (Joey)</strong>',
      bullets:[
        'Analyzes instructional patterns',
        'Highlights growth trends'
      ],
      outro:'Supports leadership conversations'
    }
  },
  8: {
    role:'District Coach',
    tagline:'Scale coaching, fidelity support, trend insights.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>District Coach Dashboard &amp; Cross-School Insight Tools</strong><br/>A clear view across classrooms, schools, and coaching efforts.',
      intro:'The district coach dashboard provides insight into instructional patterns across buildings. Examples include:',
      bullets:[
        '<strong>Cross-School Instructional Pattern Views</strong> – trends in learning and practice',
        '<strong>School-Level Coaching Focus Areas</strong> – where support is most needed',
        '<strong>Coach &amp; Building Dashboards</strong> – visibility into what school teams are seeing',
        '<strong>Implementation Growth Indicators</strong> – how practices are developing over time'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      subtitle:'<strong>Micro-Credentialing System</strong><br/>Professional learning that builds coaching expertise at scale.',
      intro:'NorthStar\'s micro-credentialing system supports district coaches in strengthening coaching practice across the system. Micro-credentials:',
      bullets:[
        'focus on coaching leadership and instructional capacity building',
        'align to district improvement priorities',
        'use real coaching artifacts and reflections as evidence',
        'are completed asynchronously within the flow of work'
      ]
    },
    coach:{
      title:'Virtual Coach',
      intro:'District virtual coach:',
      bullets:[
        'build shared schema across coaches and schools',
        'align theory, practice, and systems',
        'document growth in a district coaching portfolio'
      ]
    }
  },
  9: {
    role:'District Leadership Team',
    tagline:'Strategic monitoring, resource alignment, reporting.',
    workspace:{
      title:'Workspace Dashboard',
      subtitle:'<strong>Organize tools into categories like:</strong>',
      bullets:[
        '<strong>System Health:</strong> adoption, active use, routine consistency',
        '<strong>Implementation &amp; Fidelity:</strong> where it\'s happening, where it\'s stuck',
        '<strong>Capacity Building:</strong> micro-credential progress by role/school',
        '<strong>Coaching &amp; Support:</strong> coaching cycles, support requests, trend patterns',
        '<strong>Reporting:</strong> aligned roll-ups for leadership teams and board-ready summaries'
      ],
      subtitle2:'<strong>Dashboard &amp; System Insight Tools</strong>',
      bullets2:[
        'District-wide learning and growth views',
        'Implementation indicators',
        'Role-level dashboards',
        'Equity and priority focus views',
        'Leadership reflection tools'
      ]
    },
    pathways:{
      title:'Learning Pathways',
      intro:'Micro credentials for district leadership, aligned to district priorities:',
      bullets:[
        'Needs/self assessment → goals → personalized learning plan',
        'Evidence-based completion (artifacts that reflect actual work)',
        'Continuous improvement cycles (not one-and-done training)'
      ]
    },
    coach:{
      title:'Virtual Coach',
      intro:'Guidance that helps leaders:',
      bullets:[
        'District launch + alignment session',
        'Role-based onboarding plan',
        'Pilot-to-scale roadmap',
        'Communication templates and routines',
        'follow consistent routines (weekly/monthly/quarterly cadences)',
        'interpret what the system is telling them',
        'select next best actions (support, coaching, resourcing, communication)',
        'Analyzes district-wide patterns',
        'Highlights achievement gaps',
        'Supports wrap-around coaching decisions',
        'Equity and priority focus views',
        'Leadership reflection tools'
      ]
    }
  },
  10: {
    role:'District Admin',
    tagline:'System health, alignment, implementation visibility, and support targeting.',
    workspace:{
      title:'Workspace Dashboard',
      bullets:[
        '<strong>Tools</strong> (embedded workflows that make the job easier)'
      ],
      body:'A centralized workspace designed for instructional leadership and implementation.',
      subtitle2:'<strong>The dashboard provides:</strong>',
      bullets2:[
        'school-wide learning trends',
        'instructional implementation indicators',
        'visibility into coaching and professional learning',
        'progress toward school goals',
        'alignment to standards and district priorities'
      ],
      outro:'Everything is organized into <strong>clear signals</strong>, not disconnected data points.'
    },
    pathways:{
      title:'Learning Pathways',
      bullets:[
        'Adults get micro-credentials that start with needs, set goals, deliver PD, and measure evidence.'
      ],
      subtitle2:'<strong>— Supporting Leadership Routines</strong>',
      intro2:'NorthStar\'s virtual systems coach supports school administrators by:',
      bullets2:[
        'reinforcing consistent leadership routines',
        'helping interpret system-level insights',
        'prompting reflection and next steps',
        'supporting alignment across roles'
      ],
      outro:'The coach helps administrators stay focused on what matters most — learning and instruction.'
    },
    coach:{
      title:'Virtual Coach',
      intro:'For school administrators, Joey is the system intelligence that turns daily classroom activity into <strong>actionable school-level insight</strong>.<br/><br/>Joey:',
      bullets:[
        'aggregates assessment and learning evidence across classrooms',
        'analyzes instructional and learning patterns over time',
        'connects student outcomes to instructional practices',
        'organizes evidence by grade, team, role, and standard'
      ]
    }
  }
};

/* Rainbow tier colors top→bottom (matches reference pyramid art) */
const tierColors = [
  '#9DD2EE', // 1 Student      - light blue
  '#5FB9E1', // 2 Family       - sky blue
  '#67C8A0', // 3 Teacher      - mint green
  '#B6D955', // 4 Interventionist - lime
  '#F4D247', // 5 Coach        - yellow
  '#F4B83D', // 6 School Leadership Team - gold
  '#ED8E45', // 7 School Admin - orange
  '#E66E4F', // 8 District Coach - red-orange
  '#D260A5', // 9 District Leadership Team - pink
  '#963E94'  // 10 District Admin - purple
];

/* Build the SVG pyramid (10 tiers) */
function buildPyramid(){
  const svg = document.getElementById('pyramidSvg');
  if (!svg) return;
  const W = 560, H = 600;
  const apex = {x: W/2, y: 60};
  const base = {leftX: 30, rightX: W - 30, y: H - 30};

  const tierHeight = (base.y - apex.y) / 10;
  const layersGroup = svg.querySelector('#layers');
  layersGroup.innerHTML = '';

  // Star above apex
  const star = document.createElementNS('http://www.w3.org/2000/svg', 'text');
  star.setAttribute('x', apex.x);
  star.setAttribute('y', apex.y - 8);
  star.setAttribute('text-anchor', 'middle');
  star.setAttribute('font-size', '34');
  star.setAttribute('fill', '#F4C942');
  star.textContent = '★';
  layersGroup.appendChild(star);

  for (let i = 0; i < 10; i++){
    const t = i + 1;
    const yTop = apex.y + i * tierHeight;
    const yBot = apex.y + (i + 1) * tierHeight;
    const ratioTop = i / 10;
    const ratioBot = (i + 1) / 10;
    const halfTop = ((base.rightX - base.leftX) / 2) * ratioTop;
    const halfBot = ((base.rightX - base.leftX) / 2) * ratioBot;

    let pts;
    if (i === 0){
      pts = `${apex.x},${apex.y} ${apex.x - halfBot},${yBot} ${apex.x + halfBot},${yBot}`;
    } else {
      pts = `${apex.x - halfTop},${yTop} ${apex.x + halfTop},${yTop} ${apex.x + halfBot},${yBot} ${apex.x - halfBot},${yBot}`;
    }

    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.setAttribute('class', 'layer');
    g.setAttribute('data-layer', t);
    g.setAttribute('tabindex','0');
    g.setAttribute('role','button');
    g.setAttribute('aria-label', `Tier ${t}: ${tierData[t].role}`);
    g.style.cursor = 'pointer';

    const poly = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
    poly.setAttribute('points', pts);
    poly.setAttribute('fill', tierColors[i]);
    poly.setAttribute('stroke', 'rgba(255,255,255,.65)');
    poly.setAttribute('stroke-width', '1.5');
    g.appendChild(poly);

    // role label centered in tier
    const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
    label.setAttribute('x', apex.x);
    // pull tier-1 label down toward the bottom of its triangle so it fits
    label.setAttribute('y', i === 0 ? yBot - 6 : (yTop + yBot) / 2 + 5);
    label.setAttribute('text-anchor', 'middle');
    label.setAttribute('font-family', 'Manrope, system-ui, sans-serif');
    label.setAttribute('font-weight', '700');
    label.setAttribute('font-size', i === 0 ? '11' : (i < 4 ? '13' : i < 7 ? '15' : 16));
    label.setAttribute('fill', i === 9 ? '#FFFFFF' : '#1A1A1A');
    label.setAttribute('pointer-events', 'none');
    label.textContent = tierData[t].role;
    g.appendChild(label);

    g.addEventListener('click', () => openTier(t));
    g.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' '){ e.preventDefault(); openTier(t); }
    });

    layersGroup.appendChild(g);
  }
}
buildPyramid();

/* ===== Tier modal ===== */
const tierModal = document.getElementById('tierModal');
const tierBody = document.getElementById('tierModalBody');

function openTier(t){
  const d = tierData[t];
  if (!d) return;
  document.querySelectorAll('.pyramid-svg .layer').forEach(n => n.classList.remove('active'));
  const node = document.querySelector(`.layer[data-layer="${t}"]`);
  if (node) node.classList.add('active');

  const renderBullets = (bullets) => bullets && bullets.length
    ? `<ul class="tp-list">${bullets.map(b => `<li><span class="tp-bullet-text">${b}</span></li>`).join('')}</ul>`
    : '';
  const renderCol = (col) => `
    <div class="tp-col">
      <h4 class="tp-col-title">${col.title}</h4>
      ${col.subtitle ? `<p class="tp-col-sub">${col.subtitle}</p>` : ''}
      ${col.intro ? `<p class="tp-col-intro">${col.intro}</p>` : ''}
      ${renderBullets(col.bullets)}
      ${col.body ? `<p class="tp-col-intro">${col.body}</p>` : ''}
      ${col.subtitle2 ? `<p class="tp-col-sub tp-col-sub-2">${col.subtitle2}</p>` : ''}
      ${col.intro2 ? `<p class="tp-col-intro">${col.intro2}</p>` : ''}
      ${renderBullets(col.bullets2)}
      ${col.outro ? `<p class="tp-col-outro">${col.outro}</p>` : ''}
    </div>
  `;

  tierBody.style.setProperty('--tier-color', tierColors[t-1]);
  tierBody.innerHTML = `
    <button class="close" aria-label="Close">×</button>
    <div class="tier-panel-inner">
      <div class="tier-head">
        <span class="tier-num">Tier ${t} of 10</span>
        <h2 class="tier-title">${d.role} <span class="tier-title-suffix">— Pillars of Support</span></h2>
        <p class="tier-tag">${d.tagline}</p>
      </div>
      <div class="three-pillars">
        ${renderCol(d.workspace)}
        ${renderCol(d.pathways)}
        ${renderCol(d.coach)}
      </div>
    </div>
  `;
  tierModal.classList.add('open');
  document.body.style.overflow = 'hidden';
  tierBody.querySelector('.close').addEventListener('click', closeTier);
}
function closeTier(){
  tierModal.classList.remove('open');
  document.body.style.overflow = '';
  document.querySelectorAll('.pyramid-svg .layer').forEach(n => n.classList.remove('active'));
}
tierModal.addEventListener('click', (e) => {
  if (e.target === tierModal) closeTier();
});
window.addEventListener('keydown', (e) => {
  if (e.key === 'Escape'){ closeTier(); closeInfo(); }
});

/* ================================================================
   Info modal — Page 10 popups
================================================================ */
const infoData = {
  team: {
    tag:'Our People',
    title:'Meet the Team',
    body:`<p>NorthStarET is led by veteran educators, instructional coaches, and continuous-improvement leaders who have lived inside districts for decades. Our team brings classroom credibility, district-leadership experience, and modern product craft to every layer of the system.</p>
          <p>Founder Beth Swenson developed the North Star Student Support Structure in 2020 as a unifying framework for the way districts actually work. Joining her are instructional designers, learning scientists, and experienced school administrators — all building tools they wish they had had themselves.</p>`
  },
  start: {
    tag:'Origin Story',
    title:'How We Got Our Start',
    body:`<p>NorthStar began the way every good improvement story begins — inside a real district, with real leaders trying to solve a real problem: too many tools, too many initiatives, and not enough coherence.</p>
          <p>What started as a hand-drawn pyramid on a meeting-room whiteboard grew into a complete system: a shared structure, shared language, and a shared set of tools that every role in a school could use, every day. That whiteboard sketch is now the North Star pyramid you see today.</p>`
  },
  now: {
    tag:'Roadmap',
    title:'Now and When — Where We\'ll Grow With Your Support',
    body:`<p><strong>Now:</strong> A complete role-based platform with workspaces for ten roles, the Joey learning intelligence, the science-of-reading–aligned PreK–8 written-code continuum, and an interactive continuous improvement plan.</p>
          <p><strong>Next:</strong> Math content alignment, expanded coaching pathways, and stronger family workspaces.</p>
          <p><strong>Then:</strong> Open APIs for assessment partners, deeper analytics, and a research practice partnership program.</p>
          <p>With your support, we accelerate the roadmap and bring NorthStar to more districts faster — without compromising on the depth that makes it work.</p>`
  },
  stories: {
    tag:'Proof',
    title:'Success Stories',
    body:`<p>From a small rural district to a fast-growing suburban network, NorthStar partners are seeing what coherence makes possible: aligned coaching, stronger instructional implementation, and better student growth — without adding pressure to schools.</p>
          <p>Pilot districts report deeper teacher engagement with professional learning, more confident leadership conversations grounded in real evidence, and clearer pathways for students and families. Full case studies are available on request.</p>`
  }
};
const infoModal = document.getElementById('infoModal');
const infoBody = document.getElementById('infoModalBody');
function openInfo(key){
  const d = infoData[key];
  if (!d) return;
  infoBody.innerHTML = `
    <button class="close" aria-label="Close">×</button>
    <span class="info-tag">${d.tag}</span>
    <h2>${d.title}</h2>
    ${d.body}
  `;
  infoModal.classList.add('open');
  document.body.style.overflow = 'hidden';
  infoBody.querySelector('.close').addEventListener('click', closeInfo);
}
function closeInfo(){
  infoModal.classList.remove('open');
  document.body.style.overflow = '';
}
infoModal.addEventListener('click', (e) => {
  if (e.target === infoModal) closeInfo();
});
document.querySelectorAll('[data-info]').forEach(el => {
  el.addEventListener('click', (e) => {
    e.preventDefault();
    openInfo(el.getAttribute('data-info'));
  });
});
